resources:
- cluster_ip.yaml
- nodeport.yaml
- loadbalancer.yaml
- internal_loadbalancer.yaml
- ingress.yaml
- container-native-neg.yaml
- container-native-ingress-lb.yaml
- container-native-ingress-ilb.yaml